### ISSUE TITLE
MF3 won't launch

### ISSUE THREAD

**Issue by ChaseThePyro** [jadedcat/MF3Configs#25]
I don't get a crash report, however, the launcher gives me this output:

[18:57:28] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:57:28] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
    at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

If anyone has any advice or solutions, they would be greatly appreciated.

**Comment by Shadowd1** [comment]
I can't get it to launch either. My crash report is here 

http://pastebin.com/Y6kqDGuM. 

I am wondering if it is that I am using too new of java. Does anyone have an idea?

**Comment by ghost** [comment]
Seems like a buggy version of forge has been downloaded. Try forcing an update of the modpack.

**Comment by ghost** [comment]
Corrupted forge installation;
1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
5. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
6. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
7. Restart pack
